// src/components/dialog/angular-wc/angular-custom-element.component.ts
import {Component, Input, OnDestroy, OnInit} from '@angular/core';

@Component({
    selector: 'app-my-web',
    template: `
        <p>Это мой веб-компонент!</p>
        <button (click)="onClick()">Нажми меня</button>
    `,
    standalone: true
})
export class AngularCustomElement implements OnInit, OnDestroy {
    ngOnInit() {
        console.log('MyWebComponent добавлен в DOM');
    }

    ngOnDestroy() {
        console.log('MyWebComponent удален из DOM');
    }

    onClick() {
        console.log('Ты нажал меня')
    }
}

// src/components/dialog/normal-wc/custom.element.ts
export class CustomElement extends HTMLElement {
    constructor() {
        super();
        const shadow = this.attachShadow({ mode: 'open' });
        const wrapper = document.createElement('div');
        wrapper.innerHTML = `
      <p>Это мой веб-компонент!</p>
      <button id="myButton">Нажми меня</button>
    `;
        shadow.appendChild(wrapper);

        const button = wrapper.querySelector('#myButton');
        button?.addEventListener('click', () => {
            console.log('Ты нажал меня CustomElement');
        });
    }

    connectedCallback() {
        console.log('MyWebComponent добавлен в DOM');
    }

    disconnectedCallback() {
        console.log('MyWebComponent удален из DOM');
    }
}
